spring.application.name=travelfans
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.rwnoqbdtbqdhshduthiw&password=travelfans2026
spring.datasource.username=postgres.rwnoqbdtbqdhshduthiw
spring.datasource.password=travelfans2026
spring.datasource.driver-class-name=org.postgresql.Driver